services:
  frontend:
    image: mon62/btw-frontend:1
    container_name: frontend
    ports:
      - 5001:5001
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    image: mon62/btw-backend:1
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - react-express
    expose: 
      - 5000
    ports:
      - 5000:5000
networks:
  react-express:
